export const overlayTemplates = {
  zoom_effect: {
    aspect_ratios: {
      '16:9': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 50,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 54,
            primary_colour: '&H00FFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
        },
      },
      '9:16': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 60,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 60,
            primary_colour: '&H00FFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
        },
      },
      '1:1': {
        styles: {
          Default: {
           fontname: 'Bebas Neue',
            fontsize: 60,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
          bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
          Highlight: {
           fontname: 'Bebas Neue',
            fontsize: 60,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
        },
      },
    },
  },

  stylish_slices_product: {
    aspect_ratios: {
      '16:9': {
        styles: {
          Default: {
            fontname: 'Cooper Black',
            fontsize: 50,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&H00FFFFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 1,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 30,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Cooper Black',
            fontsize: 60,
            primary_colour: '&H00FFFF',
            secondary_colour: '&H00FF00&',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 1,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 30,
            encoding: 1,
          },
          CenterBox: {
            fontname: 'Cooper Black',
            fontsize: 60,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&H00FF00&',
            outline_colour: '&H00000000',
            back_colour: '&H80808080',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 4,
            outline: 2,
            shadow: 1,
            alignment: 5,
            margin_l: 20,
            margin_r: 20,
            margin_v: 0,
            encoding: 1,
          },
          LeftOverlay: {
            fontname: 'Cooper Black',
            fontsize: 60,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&H00FFFFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 1,
            alignment: 4,
            margin_l: 16,
            margin_r: 320,
            margin_v: 400,
            encoding: 1,
            left_frame_width_percent: 0.42,
            padding_percent: 0.05,
          },
          LeftOverlayHighlight: {
            fontname: 'Cooper Black',
            fontsize: 60,
            primary_colour: '&H00FFFF',
            secondary_colour: '&H00FFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 1,
            alignment: 4,
            margin_l: 16,
            margin_r: 320,
            margin_v: 400,
            encoding: 1,
            left_frame_width_percent: 0.42,
            padding_percent: 0.05,
          },
          CenterBoxHighlight: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFF',
            secondary_colour: '&H00FFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 4,
            outline: 2,
            shadow: 1,
            alignment: 5,
            margin_l: 25,
            margin_r: 25,
            margin_v: 0,
            encoding: 1,
          },
        },
      },
      '9:16': {
        styles: {
          Default: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&H00FFFFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 3,
            shadow: 2,
            alignment: 2,
            margin_l: 15,
            margin_r: 15,
            margin_v: 30,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFF',
            secondary_colour: '&H0000FFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 3,
            shadow: 2,
            alignment: 2,
            margin_l: 15,
            margin_r: 15,
            margin_v: 30,
            encoding: 1,
          },
          CenterBox: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&H00FFFFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80808080',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 4,
            outline: 3,
            shadow: 2,
            alignment: 5,
            margin_l: 30,
            margin_r: 30,
            margin_v: 0,
            encoding: 1,
          },
          LeftOverlay: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&H00FFFFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 3,
            shadow: 2,
            alignment: 4,
            margin_l: 10,
            margin_r: 50,
            margin_v: 50,
            encoding: 1,
            left_frame_width_percent: 0.42,
            padding_percent: 0.05,
          },
          LeftOverlayHighlight: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFF',
            secondary_colour: '&H00FFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 1,
            alignment: 4,
            margin_l: 10,
            margin_r: 50,
            margin_v: 50,
            encoding: 1,
            left_frame_width_percent: 0.42,
            padding_percent: 0.05,
          },
          CenterBoxHighlight: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFF',
            secondary_colour: '&H00FFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 4,
            outline: 2,
            shadow: 1,
            alignment: 5,
            margin_l: 25,
            margin_r: 25,
            margin_v: 0,
            encoding: 1,
          },
        },
      },
      '1:1': {
        styles: {
          Default: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&H00FFFFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 1,
            alignment: 2,
            margin_l: 12,
            margin_r: 12,
            margin_v: 30,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H0000FFFF',
            secondary_colour: '&H0000FFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 1,
            alignment: 2,
            margin_l: 12,
            margin_r: 12,
            margin_v: 30,
            encoding: 1,
          },
          CenterBox: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&H00FFFFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80808080',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 4,
            outline: 2,
            shadow: 1,
            alignment: 5,
            margin_l: 25,
            margin_r: 25,
            margin_v: 0,
            encoding: 1,
          },
          LeftOverlay: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&H00FFFFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 1,
            alignment: 4,
            margin_l: 8,
            margin_r: 45,
            margin_v: 50,
            encoding: 1,
            left_frame_width_percent: 0.42,
            padding_percent: 0.05,
          },
          LeftOverlayHighlight: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFF',
            secondary_colour: '&H00FFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 1,
            alignment: 4,
            margin_l: 8,
            margin_r: 45,
            margin_v: 50,
            encoding: 1,
            left_frame_width_percent: 0.42,
            padding_percent: 0.05,
          },
          CenterBoxHighlight: {
            fontname: 'Cooper Black',
            fontsize: 10,
            primary_colour: '&H00FFFF',
            secondary_colour: '&H00FFFF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 4,
            outline: 2,
            shadow: 1,
            alignment: 5,
            margin_l: 25,
            margin_r: 25,
            margin_v: 0,
            encoding: 1,
          },
        },
      },
    },
  },
};
