export const overlayTemplates = {
  basic: {
    aspect_ratios: {
      '16:9': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 14,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 14,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
        },
      },
      '9:16': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 14,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 14,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
        },
      },
      '1:1': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 14,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 14,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
        },
      },
    },
  },

  zoom_effect: {
    aspect_ratios: {
      '16:9': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 50,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 54,
            primary_colour: '&H00FFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
        },
      },
      '9:16': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 60,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 60,
            primary_colour: '&H00FFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
        },
      },
      '1:1': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 60,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 60,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 40,
            encoding: 1,
          },
        },
      },
    },
  },

  card_motion: {
    aspect_ratios: {
      '16:9': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 40,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 30,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 40,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 30,
            encoding: 1,
          },
        },
      },
      '9:16': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 40,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 30,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 35,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 30,
            encoding: 1,
          },
        },
      },
      '1:1': {
        styles: {
          Default: {
            fontname: 'Bebas Neue',
            fontsize: 35,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 30,
            encoding: 1,
          },
          Highlight: {
            fontname: 'Bebas Neue',
            fontsize: 35,
            primary_colour: '&H00FFFFFF',
            secondary_colour: '&&H000000FF',
            outline_colour: '&H00000000',
            back_colour: '&H80000000',
            bold: 0,
            italic: 0,
            underline: 0,
            strikeout: 0,
            scale_x: 100,
            scale_y: 100,
            spacing: 0,
            angle: 0,
            border_style: 1,
            outline: 2,
            shadow: 6,
            alignment: 2,
            margin_l: 10,
            margin_r: 10,
            margin_v: 30,
            encoding: 1,
          },
        },
      },
    },
  },


cycle: {
  aspect_ratios: {
    '16:9': {
      styles: {
        // 1. ZOOM_IN - Clean White with Blue Highlight (Simple & Professional)
        Default: {
          fontname: 'Cooper Black',
          fontsize: 55,
          primary_colour: '&H00FFFFFF',      // White text
          secondary_colour: '&H00FF6B00',    // Orange highlight (karaoke)
          outline_colour: '&H00000000',      // Black outline
          back_colour: '&H80000000',         // Semi-transparent black
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 2,                      // Bottom center
          margin_l: 10,
          margin_r: 10,
          margin_v: 40,
          encoding: 1,
        },

        // 2. ZOOM_OUT - Bright Yellow with Cyan Box (Eye-catching)
        Highlight: {
          fontname: 'Cooper Black',
          fontsize: 58,
          primary_colour: '&H0000FFFF',      // Bright Yellow
          secondary_colour: '&H0000FF00',    // Cyan highlight (karaoke)
          outline_colour: '&H00000000',      // Black outline
          back_colour: '&HA0202020',         // Dark semi-transparent
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 1,
          angle: 0,
          border_style: 3,                   // Box background
          outline: 3,
          shadow: 2,
          alignment: 2,                      // Bottom center
          margin_l: 20,
          margin_r: 20,
          margin_v: 35,
          encoding: 1,
        },

        // 3. WIPE_LEFT - Center Box with Pink/Purple Theme
        CenterBox: {
          fontname: 'Cooper Black',
          fontsize: 62,
          primary_colour: '&H00FFFFFF',      // White text
          secondary_colour: '&H00FF00FF',    // Magenta highlight (karaoke)
          outline_colour: '&H00000000',      // Black outline
          back_colour: '&HC0404040',         // Gray box (75% opacity)
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 4,                   // Box with padding
          outline: 2,
          shadow: 1,
          alignment: 5,                      // Center middle
          margin_l: 30,
          margin_r: 30,
          margin_v: 0,
          encoding: 1,
        },

        // 4. WHITE_BOX (40%) - Left Text with Green Theme
        LeftOverlay: {
          fontname: 'Cooper Black',
          fontsize: 56,
          primary_colour: '&H00FFFFFF',      // White text
          secondary_colour: '&H0000FF00',    // Lime Green highlight (karaoke)
          outline_colour: '&H00000000',      // Black outline
          back_colour: '&H00000000',         // Transparent (box already there)
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 4,                      // Left middle
          margin_l: 40,                      // Inside 40% box
          margin_r: 600,                     // Keep on left side
          margin_v: 0,
          encoding: 1,
          left_frame_width_percent: 0.4,
          padding_percent: 0.05,
        },

        // 5. ZOOM_OUT - Left Highlighted Orange/Red Theme
        LeftOverlayHighlight: {
          fontname: 'Cooper Black',
          fontsize: 56,
          primary_colour: '&H0000CCFF',      // Orange text
          secondary_colour: '&H000000FF',    // Red highlight (karaoke)
          outline_colour: '&H00000000',      // Black outline
          back_colour: '&H00000000',         // Transparent
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 4,                      // Left middle
          margin_l: 40,
          margin_r: 600,
          margin_v: 0,
          encoding: 1,
          left_frame_width_percent: 0.4,
          padding_percent: 0.05,
        },

        // 6. ZOOM_OUT - Simple Blue Theme (Clean)
        SimpleBlue: {
          fontname: 'Cooper Black',
          fontsize: 54,
          primary_colour: '&H00FFFF00',      // Cyan text
          secondary_colour: '&H00FF6600',    // Blue-Orange highlight (karaoke)
          outline_colour: '&H00000000',      // Black outline
          back_colour: '&H80000000',         // Semi-transparent black
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 2,                      // Bottom center
          margin_l: 10,
          margin_r: 10,
          margin_v: 40,
          encoding: 1,
        },

        // 7. WIPE_RIGHT - Center Highlighted Purple/Pink Box
        CenterBoxHighlight: {
          fontname: 'Cooper Black',
          fontsize: 60,
          primary_colour: '&H00FF99FF',      // Light Pink text
          secondary_colour: '&H00FF00FF',    // Magenta highlight (karaoke)
          outline_colour: '&H00000000',      // Black outline
          back_colour: '&HC0502050',         // Purple box (75% opacity)
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 4,                   // Box with padding
          outline: 2,
          shadow: 1,
          alignment: 5,                      // Center middle
          margin_l: 35,
          margin_r: 35,
          margin_v: 0,
          encoding: 1,
        },

        // 8. WHITE_BOX (Last) - Left Yellow Theme
        LeftYellow: {
          fontname: 'Cooper Black',
          fontsize: 56,
          primary_colour: '&H0000FFFF',      // Yellow text
          secondary_colour: '&H0000CCFF',    // Orange highlight (karaoke)
          outline_colour: '&H00000000',      // Black outline
          back_colour: '&H00000000',         // Transparent
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 4,                      // Left middle
          margin_l: 40,
          margin_r: 600,
          margin_v: 0,
          encoding: 1,
          left_frame_width_percent: 0.4,
          padding_percent: 0.05,
        },
      },
    },

    '9:16': {
      styles: {
        // Mobile Portrait - Same colors, adjusted sizes
        Default: {
          fontname: 'Cooper Black',
          fontsize: 48,
          primary_colour: '&H00FFFFFF',
          secondary_colour: '&H00FF6B00',
          outline_colour: '&H00000000',
          back_colour: '&H80000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 2,
          margin_l: 15,
          margin_r: 15,
          margin_v: 50,
          encoding: 1,
        },
        Highlight: {
          fontname: 'Cooper Black',
          fontsize: 50,
          primary_colour: '&H0000FFFF',
          secondary_colour: '&H0000FF00',
          outline_colour: '&H00000000',
          back_colour: '&HA0202020',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 1,
          angle: 0,
          border_style: 3,
          outline: 3,
          shadow: 2,
          alignment: 2,
          margin_l: 20,
          margin_r: 20,
          margin_v: 45,
          encoding: 1,
        },
        CenterBox: {
          fontname: 'Cooper Black',
          fontsize: 52,
          primary_colour: '&H00FFFFFF',
          secondary_colour: '&H00FF00FF',
          outline_colour: '&H00000000',
          back_colour: '&HC0404040',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 4,
          outline: 2,
          shadow: 1,
          alignment: 5,
          margin_l: 40,
          margin_r: 40,
          margin_v: 0,
          encoding: 1,
        },
        LeftOverlay: {
          fontname: 'Cooper Black',
          fontsize: 46,
          primary_colour: '&H00FFFFFF',
          secondary_colour: '&H0000FF00',
          outline_colour: '&H00000000',
          back_colour: '&H00000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 4,
          margin_l: 25,
          margin_r: 100,
          margin_v: 0,
          encoding: 1,
        },
        LeftOverlayHighlight: {
          fontname: 'Cooper Black',
          fontsize: 46,
          primary_colour: '&H0000CCFF',
          secondary_colour: '&H000000FF',
          outline_colour: '&H00000000',
          back_colour: '&H00000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 4,
          margin_l: 25,
          margin_r: 100,
          margin_v: 0,
          encoding: 1,
        },
        SimpleBlue: {
          fontname: 'Cooper Black',
          fontsize: 46,
          primary_colour: '&H00FFFF00',
          secondary_colour: '&H00FF6600',
          outline_colour: '&H00000000',
          back_colour: '&H80000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 2,
          margin_l: 15,
          margin_r: 15,
          margin_v: 50,
          encoding: 1,
        },
        CenterBoxHighlight: {
          fontname: 'Cooper Black',
          fontsize: 50,
          primary_colour: '&H00FF99FF',
          secondary_colour: '&H00FF00FF',
          outline_colour: '&H00000000',
          back_colour: '&HC0502050',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 4,
          outline: 2,
          shadow: 1,
          alignment: 5,
          margin_l: 45,
          margin_r: 45,
          margin_v: 0,
          encoding: 1,
        },
        LeftYellow: {
          fontname: 'Cooper Black',
          fontsize: 46,
          primary_colour: '&H0000FFFF',
          secondary_colour: '&H0000CCFF',
          outline_colour: '&H00000000',
          back_colour: '&H00000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 4,
          margin_l: 25,
          margin_r: 100,
          margin_v: 0,
          encoding: 1,
        },
      },
    },

    '1:1': {
      styles: {
        // Square Format - Same colors, adjusted sizes
        Default: {
          fontname: 'Cooper Black',
          fontsize: 50,
          primary_colour: '&H00FFFFFF',
          secondary_colour: '&H00FF6B00',
          outline_colour: '&H00000000',
          back_colour: '&H80000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 2,
          margin_l: 12,
          margin_r: 12,
          margin_v: 40,
          encoding: 1,
        },
        Highlight: {
          fontname: 'Cooper Black',
          fontsize: 52,
          primary_colour: '&H0000FFFF',
          secondary_colour: '&H0000FF00',
          outline_colour: '&H00000000',
          back_colour: '&HA0202020',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 1,
          angle: 0,
          border_style: 3,
          outline: 3,
          shadow: 2,
          alignment: 2,
          margin_l: 18,
          margin_r: 18,
          margin_v: 35,
          encoding: 1,
        },
        CenterBox: {
          fontname: 'Cooper Black',
          fontsize: 54,
          primary_colour: '&H00FFFFFF',
          secondary_colour: '&H00FF00FF',
          outline_colour: '&H00000000',
          back_colour: '&HC0404040',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 4,
          outline: 2,
          shadow: 1,
          alignment: 5,
          margin_l: 30,
          margin_r: 30,
          margin_v: 0,
          encoding: 1,
        },
        LeftOverlay: {
          fontname: 'Cooper Black',
          fontsize: 48,
          primary_colour: '&H00FFFFFF',
          secondary_colour: '&H0000FF00',
          outline_colour: '&H00000000',
          back_colour: '&H00000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 4,
          margin_l: 30,
          margin_r: 500,
          margin_v: 0,
          encoding: 1,
        },
        LeftOverlayHighlight: {
          fontname: 'Cooper Black',
          fontsize: 48,
          primary_colour: '&H0000CCFF',
          secondary_colour: '&H000000FF',
          outline_colour: '&H00000000',
          back_colour: '&H00000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 4,
          margin_l: 30,
          margin_r: 500,
          margin_v: 0,
          encoding: 1,
        },
        SimpleBlue: {
          fontname: 'Cooper Black',
          fontsize: 48,
          primary_colour: '&H00FFFF00',
          secondary_colour: '&H00FF6600',
          outline_colour: '&H00000000',
          back_colour: '&H80000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 2,
          margin_l: 12,
          margin_r: 12,
          margin_v: 40,
          encoding: 1,
        },
        CenterBoxHighlight: {
          fontname: 'Cooper Black',
          fontsize: 52,
          primary_colour: '&H00FF99FF',
          secondary_colour: '&H00FF00FF',
          outline_colour: '&H00000000',
          back_colour: '&HC0502050',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 4,
          outline: 2,
          shadow: 1,
          alignment: 5,
          margin_l: 35,
          margin_r: 35,
          margin_v: 0,
          encoding: 1,
        },
        LeftYellow: {
          fontname: 'Cooper Black',
          fontsize: 48,
          primary_colour: '&H0000FFFF',
          secondary_colour: '&H0000CCFF',
          outline_colour: '&H00000000',
          back_colour: '&H00000000',
          bold: -1,
          italic: 0,
          underline: 0,
          strikeout: 0,
          scale_x: 100,
          scale_y: 100,
          spacing: 0,
          angle: 0,
          border_style: 1,
          outline: 3,
          shadow: 2,
          alignment: 4,
          margin_l: 30,
          margin_r: 500,
          margin_v: 0,
          encoding: 1,
        },
      },
    },
  },
}

  // cycle: {
  //   aspect_ratios: {
  //     '16:9': {
  //       styles: {
  //         Default: {
  //           fontname: 'Cooper Black',
  //           fontsize: 50,
  //           primary_colour: '&H00FFFFFF',
  //           secondary_colour: '&H00FFFFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 2,
  //           margin_l: 10,
  //           margin_r: 10,
  //           margin_v: 30,
  //           encoding: 1,
  //         },
  //         Highlight: {
  //           fontname: 'Cooper Black',
  //           fontsize: 60,
  //           primary_colour: '&H00FFFF',
  //           secondary_colour: '&H00FF00&',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 2,
  //           margin_l: 10,
  //           margin_r: 10,
  //           margin_v: 30,
  //           encoding: 1,
  //         },
  //         CenterBox: {
  //           fontname: 'Cooper Black',
  //           fontsize: 60,
  //           primary_colour: '&H00FFFFFF',
  //           secondary_colour: '&H00FF00&',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80808080',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 4,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 5,
  //           margin_l: 20,
  //           margin_r: 20,
  //           margin_v: 0,
  //           encoding: 1,
  //         },
  //         LeftOverlay: {
  //           fontname: 'Cooper Black',
  //           fontsize: 60,
  //           primary_colour: '&H00FFFFFF',
  //           secondary_colour: '&H00FFFFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 4,
  //           margin_l: 16,
  //           margin_r: 320,
  //           margin_v: 400,
  //           encoding: 1,
  //           left_frame_width_percent: 0.42,
  //           padding_percent: 0.05,
  //         },
  //         LeftOverlayHighlight: {
  //           fontname: 'Cooper Black',
  //           fontsize: 60,
  //           primary_colour: '&H00FFFF',
  //           secondary_colour: '&H00FFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 4,
  //           margin_l: 16,
  //           margin_r: 320,
  //           margin_v: 400,
  //           encoding: 1,
  //           left_frame_width_percent: 0.42,
  //           padding_percent: 0.05,
  //         },
  //         CenterBoxHighlight: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFF',
  //           secondary_colour: '&H00FFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 4,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 5,
  //           margin_l: 25,
  //           margin_r: 25,
  //           margin_v: 0,
  //           encoding: 1,
  //         },
  //       },
  //     },

  //     '9:16': {
  //       styles: {
  //         Default: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFFFF',
  //           secondary_colour: '&H00FFFFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 3,
  //           shadow: 2,
  //           alignment: 2,
  //           margin_l: 15,
  //           margin_r: 15,
  //           margin_v: 30,
  //           encoding: 1,
  //         },
  //         Highlight: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFF',
  //           secondary_colour: '&H0000FFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 3,
  //           shadow: 2,
  //           alignment: 2,
  //           margin_l: 15,
  //           margin_r: 15,
  //           margin_v: 30,
  //           encoding: 1,
  //         },
  //         CenterBox: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFFFF',
  //           secondary_colour: '&H00FFFFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80808080',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 4,
  //           outline: 3,
  //           shadow: 2,
  //           alignment: 5,
  //           margin_l: 30,
  //           margin_r: 30,
  //           margin_v: 0,
  //           encoding: 1,
  //         },
  //         LeftOverlay: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFFFF',
  //           secondary_colour: '&H00FFFFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 3,
  //           shadow: 2,
  //           alignment: 4,
  //           margin_l: 10,
  //           margin_r: 50,
  //           margin_v: 50,
  //           encoding: 1,
  //           left_frame_width_percent: 0.42,
  //           padding_percent: 0.05,
  //         },
  //         LeftOverlayHighlight: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFF',
  //           secondary_colour: '&H00FFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 4,
  //           margin_l: 10,
  //           margin_r: 50,
  //           margin_v: 50,
  //           encoding: 1,
  //           left_frame_width_percent: 0.42,
  //           padding_percent: 0.05,
  //         },
  //         CenterBoxHighlight: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFF',
  //           secondary_colour: '&H00FFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 4,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 5,
  //           margin_l: 25,
  //           margin_r: 25,
  //           margin_v: 0,
  //           encoding: 1,
  //         },
  //       },
  //     },

  //     '1:1': {
  //       styles: {
  //         Default: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFFFF',
  //           secondary_colour: '&H00FFFFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 2,
  //           margin_l: 12,
  //           margin_r: 12,
  //           margin_v: 30,
  //           encoding: 1,
  //         },
  //         Highlight: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H0000FFFF',
  //           secondary_colour: '&H0000FFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 2,
  //           margin_l: 12,
  //           margin_r: 12,
  //           margin_v: 30,
  //           encoding: 1,
  //         },
  //         CenterBox: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFFFF',
  //           secondary_colour: '&H00FFFFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80808080',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 4,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 5,
  //           margin_l: 25,
  //           margin_r: 25,
  //           margin_v: 0,
  //           encoding: 1,
  //         },
  //         LeftOverlay: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFFFF',
  //           secondary_colour: '&H00FFFFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 4,
  //           margin_l: 8,
  //           margin_r: 45,
  //           margin_v: 50,
  //           encoding: 1,
  //           left_frame_width_percent: 0.42,
  //           padding_percent: 0.05,
  //         },
  //         LeftOverlayHighlight: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFF',
  //           secondary_colour: '&H00FFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 1,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 4,
  //           margin_l: 8,
  //           margin_r: 45,
  //           margin_v: 50,
  //           encoding: 1,
  //           left_frame_width_percent: 0.42,
  //           padding_percent: 0.05,
  //         },
  //         CenterBoxHighlight: {
  //           fontname: 'Cooper Black',
  //           fontsize: 10,
  //           primary_colour: '&H00FFFF',
  //           secondary_colour: '&H00FFFF',
  //           outline_colour: '&H00000000',
  //           back_colour: '&H80000000',
  //           bold: 0,
  //           italic: 0,
  //           underline: 0,
  //           strikeout: 0,
  //           scale_x: 100,
  //           scale_y: 100,
  //           spacing: 0,
  //           angle: 0,
  //           border_style: 4,
  //           outline: 2,
  //           shadow: 1,
  //           alignment: 5,
  //           margin_l: 25,
  //           margin_r: 25,
  //           margin_v: 0,
  //           encoding: 1,
  //         },
  //       },
  //     },
  //   },
  // },
};
